output-format: pylint

#strictness: medium
test-warnings: false
doc-warnings: false
autodetect: true
member-warnings: false

pylint:
  disable:
    - import-error
    - django-not-available
  options:
    max-line-length: 159

pycodestyle:
  options:
    max-line-length: 159

mccabe:
  options:
    max-complexity: 10
