output-format: pylint

#strictness: medium
test-warnings: false
doc-warnings: false
autodetect: true
member-warnings: false

pylint:
  disable:
    - import-error
  options:
    max-line-length: 127

pycodestyle:
  options:
    max-line-length: 127

mccabe:
  options:
    max-complexity: 10
